server:
  port: 8080

spring:
  application:
    name: demo
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        order_inserts: true
        jdbc:
          batch_size: 10000
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: admin
    password: P@ssw0rd
    hikari:
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 40
      maximum-pool-size: 300
  schedule:
    enabled: true

demo:
  exclude:
    company:
      names:
        keyword:
    job:
      names:
        keyword:
    area:
      names:
        keyword:
  monthly:
    minimum:
      wage: 70_000
  yearly:
    minimum:
      wage: 1_000_000

logging:
  file:
    path: ./log/
    name: spider.log
  level:
    com:
      youlin:
        spider:
          demo: debug
